/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package khanzahmsservicesirsyankesC19;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.SirsApiC19;
import fungsi.koneksiDB;
import fungsi.sekuel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Properties;
import javax.swing.Timer;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;

/**
 *
 * @author windiartonugroho
 */
public class frmUtama extends javax.swing.JFrame {
    private  Properties prop = new Properties();
    private  Connection koneksi=koneksiDB.condb(),koneksi1=koneksiDB.condb();
    private  sekuel Sequel=new sekuel(),Sequel1=new sekuel();
    //private  String requestXML,URL="";
    private  SirsApiC19 api=new SirsApiC19();
    private String requestJson,requestJson1,URL="",respon="",idrs="",pass="",tot="0",tot1="";
    private  HttpHeaders headers,headers1;
    private  HttpEntity requestEntity,requestEntity1;
    private  ObjectMapper mapper= new ObjectMapper(),mapper1= new ObjectMapper();
    private  JsonNode root,root1;
    private  JsonNode nameNode,nameNode1;
    private  JsonNode response,response1;
    private  PreparedStatement ps,ps1;
    private  ResultSet rs,rs1;
    private int totaltt=0,tersedia=0,prepare=0,terpakai=0,prepare_plan=0;
    

    /**
     * Creates new form frmUtama
     */
    public frmUtama() {
            
            
        initComponents();
        try {
            prop.loadFromXML(new FileInputStream("setting/database.xml"));
            URL = prop.getProperty("URLAPISIRSC19");
            idrs=koneksiDB.IDSIRSC19();
            pass=koneksiDB.PASSSIRSC19();
            
        } catch (Exception e) {
            System.out.println("E : "+e);
        }
        
        this.setSize(390,340);
        
        jam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TeksArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMKES Khanza Service SIRANAP Versi 3.0 RS. ONLINE");

        TeksArea.setColumns(20);
        TeksArea.setRows(5);
        jScrollPane1.setViewportView(TeksArea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TeksArea;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private void jam(){
        ActionListener taskPerformer = new ActionListener(){
            private int nilai_jam;
            private int nilai_menit;
            private int nilai_detik;
            public void actionPerformed(ActionEvent e) {
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                Date now = Calendar.getInstance().getTime();
                // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
                nilai_jam = now.getHours();
                nilai_menit = now.getMinutes();
                nilai_detik = now.getSeconds();
                // Jika nilai JAM lebih kecil dari 10 (hanya 1 digit)
                if (nilai_jam <= 9) {
                    // Tambahkan "0" didepannya
                    nol_jam = "0";
                }
                // Jika nilai MENIT lebih kecil dari 10 (hanya 1 digit)
                if (nilai_menit <= 9) {
                    // Tambahkan "0" didepannya
                    nol_menit = "0";
                }
                // Jika nilai DETIK lebih kecil dari 10 (hanya 1 digit)
                if (nilai_detik <= 9) {
                    // Tambahkan "0" didepannya
                    nol_detik = "0";
                }
                // Membuat String JAM, MENIT, DETIK
                //String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                TeksArea.append(menit+":"+detik+"\n");
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                Date date = new Date();
                if(detik.equals("01")){
                    if(detik.equals("01")){
                        TeksArea.setText("");
                    }
                        
                    try {
                        koneksi=koneksiDB.condb();
                        TeksArea.append("Memulai update Siranap Versi 3.0\n");
                        ps=koneksi.prepareStatement(
                                "select count(siranap_ketersediaan_kamar_c19.ID_ruang) as jumlah_ruang,siranap_ketersediaan_kamar_c19.ID_RSONLINE,"
                                + "siranap_ketersediaan_kamar_c19.kategori,siranap_ketersediaan_kamar_c19.ID_RUANG,siranap_ketersediaan_kamar_c19.NAMA_RUANG,siranap_ketersediaan_kamar_c19.kelas,"
                                + "sum(siranap_ketersediaan_kamar_c19.kapasitas)as jumlah_bed,siranap_ketersediaan_kamar_c19.antrian, siranap_ketersediaan_kamar_c19.covid from siranap_ketersediaan_kamar_c19 inner join "
                                + "bangsal on siranap_ketersediaan_kamar_c19.ID_RUANG=bangsal.kd_bangsal where siranap_ketersediaan_kamar_c19.covid=1 GROUP BY  ID_RSONLINE");
                        
                        try {
                            rs=ps.executeQuery();
                            
                            while(rs.next()){
                                TeksArea.append("Mengirimkan kamar "+rs.getString("ID_RSONLINE")+" "+rs.getString("NAMA_RUANG")+"\n");
                                try {    
                                   // totaltt=Sequel.cariInteger("select count(kd_kamar) from kamar where statusdata='1' and kelas='"+rs.getString("kelas")+"' and kd_bangsal='"+rs.getString("ID_RUANG")+"'");
                                    //tersedia=Sequel.cariInteger("select count(kd_kamar) from kamar where statusdata='1' and kelas='"+rs.getString("kelas")+"' and status='KOSONG' and kd_bangsal='"+rs.getString("ID_RUANG")+"'");
                                    //terpakai=Sequel.cariInteger("select count(kd_kamar) from kamar where statusdata='1' and kelas='"+rs.getString("kelas")+"' and status='ISI' and kd_bangsal='"+rs.getString("ID_RUANG")+"'");
                                    //prepare=Sequel.cariInteger("select count(kd_kamar) from kamar where statusdata='1' and kelas='"+rs.getString("kelas")+"' and status='DIBERSIHKAN' and kd_bangsal='"+rs.getString("ID_RUANG")+"'");
                                    //prepare_plan=Sequel.cariInteger("select count(kd_kamar) from kamar where statusdata='1' and kelas='"+rs.getString("kelas")+"' and status='DIBOOKING' and kd_bangsal='"+rs.getString("ID_RUANG")+"'");
                                    
                                    // Ini Bagian Pengiriman Kamar Covid.............................................................
                                    
                                    headers = new HttpHeaders();
                                    headers.setContentType(MediaType.APPLICATION_JSON);
                                    headers.add("X-rs-id",idrs);
                                    headers.add("X-Timestamp",String.valueOf(api.GetUTCdatetimeAsString()));            
                                    headers.add("X-pass",pass);
                                    requestJson ="{\"id_tt\":\""+rs.getString("ID_RSONLINE")+"\", "+
                                                  "\"ruang\":\""+rs.getString("NAMA_RUANG")+"\","+ 
                                                  "\"jumlah_ruang\":\""+rs.getString("jumlah_ruang")+"\","+ 
                                                  "\"jumlah\":\""+rs.getString("jumlah_bed")+"\","+ 
                                                  "\"terpakai\":\""+Sequel.cariInteger("select count(kamar.kd_kamar) from kamar inner join siranap_ketersediaan_kamar_c19 on kamar.kd_bangsal=siranap_ketersediaan_kamar_c19.id_ruang  where statusdata='1' and kamar.kelas='"+rs.getString("kelas")+"' and kamar.status='ISI' and siranap_ketersediaan_kamar_c19.covid = '1' group by '"+rs.getString("ID_RSONLINE")+"' ")+"\","+ 
                                                  "\"terpakai_suspek\":\""+'0'+"\","+ 
                                                  "\"terpakai_konfirmasi\":\""+Sequel.cariInteger("select count(kamar.kd_kamar) from kamar inner join siranap_ketersediaan_kamar_c19 on kamar.kd_bangsal=siranap_ketersediaan_kamar_c19.id_ruang  where statusdata='1' and kamar.kelas='"+rs.getString("kelas")+"' and kamar.status='ISI' and siranap_ketersediaan_kamar_c19.covid = '1' group by '"+rs.getString("ID_RSONLINE")+"' ")+"\","+ 
                                                  "\"antrian\":\""+rs.getString("antrian")+"\","+ 
                                                  "\"prepare\":\""+'0'+"\","+ 
                                                  "\"prepare_plan\":\""+Sequel.cariInteger("select count(kd_kamar) from kamar where statusdata='1' and kelas='Kelas VIP' and status='DIBOOKING' ")+"\","+
                                                  "\"covid\":1"+
                                                  "}";
                                                  
                                   
                                    
                                    TeksArea.append("JSON dikirim : "+requestJson+"\n");
                                    requestEntity = new HttpEntity(requestJson,headers);
                                    requestJson=api.getRest().exchange(URL, HttpMethod.PUT, requestEntity, String.class).getBody();
                                    TeksArea.append("respon WS SIRANAP KEMKES V2 : "+requestJson+"\n");
                                }catch (Exception ex) {
                                    System.out.println("Notifikasi Bridging : "+ex);
                                }
                            }
                        } catch (Exception ex) {
                            System.out.println("Notif Ketersediaan : "+ex);
                        } finally{
                            if(rs!=null){
                                rs.close();
                            }
                            if(ps!=null){
                                ps.close();
                            }
                        }
                        TeksArea.append("Proses update selesai\n");
                    } catch (Exception ez) {
                        System.out.println("Notif : "+ez);
                    }
                    //bagian kamar non covid -------------------------------------------------------------------------->
                    try {
                        koneksi1=koneksiDB.condb();
                        TeksArea.append("Memulai update Siranap\n");
                        
                        ps1=koneksi1.prepareStatement(
                                "select count(siranap_ketersediaan_kamar_c19.ID_RSONLINE) as jumlah_ruang,siranap_ketersediaan_kamar_c19.ID_RSONLINE,"
                                + "siranap_ketersediaan_kamar_c19.kategori,siranap_ketersediaan_kamar_c19.ID_RUANG,siranap_ketersediaan_kamar_c19.NAMA_RUANG,"
                                + "siranap_ketersediaan_kamar_c19.kelas,siranap_ketersediaan_kamar_c19.kapasitas,siranap_ketersediaan_kamar_c19.prepare,"
                                + "siranap_ketersediaan_kamar_c19.prepare_plan,siranap_ketersediaan_kamar_c19.covid from siranap_ketersediaan_kamar_c19 "
                               + "inner join bangsal on siranap_ketersediaan_kamar_c19.ID_RUANG=bangsal.kd_bangsal "
                                + "where siranap_ketersediaan_kamar_c19.covid='0' Group BY ID_ruang");
                        try {
                            rs1=ps1.executeQuery();
                          while(rs1.next()){
                                TeksArea.append("Mengirimkan kamar "+rs1.getString("ID_RSONLINE")+" "+rs1.getString("NAMA_RUANG")+"\n");
                                try {    
                                    //totaltt=Sequel1.cariInteger("select count(kd_kamar) from kamar where statusdata='1' and kelas='"+rs.getString("kelas")+"' and kd_bangsal='"+rs.getString("kd_bangsal")+"'");
                                    //tersedia=Sequel1.cariInteger("select count(kd_kamar) from kamar where statusdata='1' and kelas='"+rs.getString("kelas")+"' and status='KOSONG' and kd_bangsal='"+rs.getString("kd_bangsal")+"'");
                                    //terpakai=Sequel1.cariInteger("select count(kd_kamar) from kamar where statusdata='1' and kelas='"+rs.getString("kelas")+"' and status='ISI' and kd_bangsal='"+rs.getString("kd_bangsal")+"'");
                                    //prepare=Sequel.cariInteger("select count(kd_kamar) from kamar where statusdata='1' and kelas='"+rs.getString("kelas")+"' and status='DIBERSIHKAN' and kd_bangsal='"+rs.getString("kd_bangsal")+"'");
                                   // Ini Bagian Pengiriman Kamar Non Covid.............................................................
                                    
                                   headers1 = new HttpHeaders();
                                  headers1.setContentType(MediaType.APPLICATION_JSON);
                                  headers1.add("X-rs-id",idrs);
                                   headers1.add("X-Timestamp",String.valueOf(api.GetUTCdatetimeAsString()));            
                                   headers1.add("X-pass",pass);
                                 requestJson1 ="{\"id_tt\":\""+rs1.getString("ID_RSONLINE")+"\", "+
                                                "\"ruang\":\""+rs1.getString("NAMA_RUANG")+"\","+ 
                                                "\"jumlah_ruang\":\""+Sequel1.cariInteger("select count(kd_kamar) from kamar where statusdata='1' and kelas='"+rs1.getString("kelas")+"' and kd_bangsal='"+rs1.getString("ID_RUANG")+"'")+"\","+ 
                                                "\"jumlah\":\""+Sequel1.cariIsi("select count(kd_kamar) from kamar where statusdata='1' and kelas='"+rs1.getString("kelas")+"' and kd_bangsal='"+rs1.getString("ID_RUANG")+"' and status='KOSONG'")+"\","+
                                                "\"terpakai\":\""+Sequel1.cariInteger("select count(kd_kamar) from kamar where statusdata='1' and kelas='"+rs1.getString("kelas")+"' and status='ISI' and kd_bangsal='"+rs1.getString("ID_RUANG")+"' and status='ISI'")+"\","+
                                                 "\"prepare\":\""+Sequel1.cariInteger("select count(kd_kamar) from kamar where statusdata='1' and kelas='"+rs1.getString("kelas")+"' and status='DIBERSIHKAN' and kd_bangsal='"+rs1.getString("ID_RUANG")+"' and status='DIBERSIHKAN'")+"\","+
                                                  "\"prepare_plan\":\""+Sequel1.cariInteger("select count(kd_kamar) from kamar where statusdata='1' and kelas='"+rs1.getString("kelas")+"' and status='DIBOOKING' and kd_bangsal='"+rs1.getString("ID_RUANG")+"' and status='DIBOOKING'")+"\","+
                                                 "\"covid\":\""+'0'+"\""+
                                                 "}";
                                  TeksArea.append("JSON dikirim : "+requestJson1+"\n");
                                    requestEntity1 = new HttpEntity(requestJson1,headers1);
                                    requestJson1=api.getRest().exchange(URL, HttpMethod.PUT, requestEntity1, String.class).getBody();
                                 TeksArea.append("respon WS SIRANAP KEMKES V2 : "+requestJson1+"\n");
                               }catch (Exception ex) {
                                   System.out.println("Notifikasi Bridging : "+ex);
                                }
                            }
                       }catch (Exception ex) {
                            System.out.println("Notif Ketersediaan : "+ex);
                        } finally{
                            if(rs1!=null){
                               rs1.close();
                            }
                            if(ps1!=null){
                               ps1.close();
                            }
                        }
                        TeksArea.append("Proses update selesai\n");
                  } catch (Exception ez) {
                      System.out.println("Notif : "+ez);
                    }
                }
            }
        };
         //Timer
        new Timer(1000, taskPerformer).start();
        }
}